FRW-8899 [WIP] Adjustments for tests

diff --git a/.ci/snippet/RERUN b/.ci/snippet/RERUN
--- a/.ci/snippet/RERUN
+++ b/.ci/snippet/RERUN
@@ -2,24 +2,30 @@
 
 set +e
 
-cmd=("${@}")
+failed=$(cat /dev/shm/failed 2>/dev/null || echo 0)
 
-echo " "
-echo "------------- ↓↓↓ Running: ${cmd[*]}"
+if [ "$failed" -gt "0" ]; then
+    echo "Detected $failed failed test(s)."
 
-"${cmd[@]}" &
-cmd_pid="${!}"
-wait "${cmd_pid}"
-status="${?}"
+    cmd=("${@}")
 
-echo -e "$((`cat /dev/shm/total` + 1))" > /dev/shm/total
+    echo "------------- ↓↓↓ Running: ${cmd[*]}"
 
-if [[ "${status}" -eq 0 ]]; then
-    echo "------------- ↑↑↑ OK"
-    echo "[✓] ${ANSI_GREEN}${cmd[*]}${ANSI_RESET}" >> /dev/shm/report
-else
-    echo "$((`cat /dev/shm/failed` + 1))" > /dev/shm/failed
-    echo "[x] ${ANSI_RED}${cmd[*]}${ANSI_RESET}" >> /dev/shm/report
-    echo "------------- ↑↑↑ ${ANSI_RED}ERROR: exited with ${status}${ANSI_RESET}"
-    echo "------------- ↑↑↑ ${ANSI_GREY}${cmd[*]}${ANSI_RESET}"
+    "${cmd[@]}" &
+    cmd_pid="${!}"
+    wait "${cmd_pid}"
+    status="${?}"
+
+    echo -e "$((`cat /dev/shm/total` + 1))" > /dev/shm/total
+
+    if [[ "${status}" -eq 0 ]]; then
+        echo "------------- ↑↑↑ OK"
+        echo "[✓] ${ANSI_GREEN}${cmd[*]}${ANSI_RESET}" >> /dev/shm/report
+    else
+        echo "$((`cat /dev/shm/failed` + 1))" > /dev/shm/failed
+
+        echo "[x] ${ANSI_RED}${cmd[*]}${ANSI_RESET}" >> /dev/shm/report
+        echo "------------- ↑↑↑ ${ANSI_RED}ERROR: exited with ${status}${ANSI_RESET}"
+        echo "------------- ↑↑↑ ${ANSI_GREY}${cmd[*]}${ANSI_RESET}"
+    fi
 fi
